### ISSUE TITLE
Excellent quality player

### ISSUE THREAD

**Issue by borisorlov21** [kevinfrei/EMP#46]
Excellent quality player I listen and on windows and rejoice the bass is dense and without distortion and excellent stereo panorama and volume thank you friend

**Comment by kevinfrei** [comment]
Thanks for the kind words. Glad you enjoy it. What platform are you using it on?

**Comment by borisorlov21** [comment]
windows11

**Comment by kevinfrei** [comment]
You just have to double-click the song and it will start playing it.

**Comment by borisorlov21** [comment]
Ок
